/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbus_adaptor /home/scott/GIT/rpi-fan-serve/dbus/org.scotthamilton.RpiFanServe.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RpiFanServeAdaptor
 */

RpiFanServeAdaptor::RpiFanServeAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RpiFanServeAdaptor::~RpiFanServeAdaptor()
{
    // destructor
}

qlonglong RpiFanServeAdaptor::cacheLifeExpectancy() const
{
    // get the value of property CacheLifeExpectancy
    return qvariant_cast< qlonglong >(parent()->property("CacheLifeExpectancy"));
}

void RpiFanServeAdaptor::setCacheLifeExpectancy(qlonglong value)
{
    // set the value of property CacheLifeExpectancy
    parent()->setProperty("CacheLifeExpectancy", QVariant::fromValue(value));
}

