/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p dbus_proxy /home/scott/GIT/rpi-fan-serve/dbus/org.scotthamilton.RpiFanServe.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus_proxy.h"

/*
 * Implementation of interface class OrgScotthamiltonRpiFanServeInterface
 */

OrgScotthamiltonRpiFanServeInterface::OrgScotthamiltonRpiFanServeInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgScotthamiltonRpiFanServeInterface::~OrgScotthamiltonRpiFanServeInterface()
{
}

